services:
  todo-app:
    build: .
    ports:
      - "3012:3012"
    environment:
      - NODE_ENV=development
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_NAME=todo_app
      - DB_USER=davidoxtoby
      - DB_PASSWORD=
      - PORT=3012
    volumes:
      # Hot reload - mount source code
      - ./:/app
      - /app/node_modules
    networks:
      - todo-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  todo-network:
    driver: bridge